initial reader + main implemented
yannlabou/par pull request #1
Opened 2021-04-03 16:01 UTC by robgineer

* CSV input data handling added: read from CSV and store into corresponding vectors

* Initial main function added: call CSV reader and cout size of each vector

2021-04-03 16:03 UTC, robgineer commented on CMakeLists.txt
> +configure_file("run_filter.h.in" "run_filter.h")
@yannlabou  not sure if this is the best way to implement a generic data path handling... any better ideas?

2021-04-03 16:04 UTC, robgineer commented on sensor_data_reader.cpp
> +    while( getline(input_file_stream, line)){
@yannlabou feel free to add a more elegant way of reading the CSV contents...

2021-04-03 16:07 UTC, robgineer commented on CMakeLists.txt
> +#add_subdirectory(src)
@yannlabou I have planned to create a source directory for each filter / data handler (once there is more code on this repo). I am ok with using a single ```src``` directory if this is what you had in mind...

2021-04-03 16:09 UTC, robgineer commented on sensor_data_reader.h
> +class SensorDataReader {
@yannlabou not sure at the moment if we will have different data handlers (other than CSVs)... if yes, we might need to change this one and inherit it one for each input type.

2021-04-03 16:12 UTC, robgineer commented on sensor_data_reader.h
> +        vector<double> getSensor1Y();
@yannlabou we would definitely have more than just one sensor output. We might want to think of a more generic way to return the data. Maybe a multidimensional vector?

2021-04-03 16:41 UTC, yannlabou commented on CMakeLists.txt
> +project(probablistic_filters CXX)
Good catch! :^)

2021-04-03 16:43 UTC, yannlabou commented on CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 17)
This is not necessary. See `target_compile_features(project_options INTERFACE cxx_std_17)`

2021-04-03 16:54 UTC, robgineer commented on CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 17)
I thought so too but I cant get a successful compile run without this...

2021-04-03 17:25 UTC, yannlabou requested changes

2021-04-03 17:25 UTC, yannlabou commented on sensor_data_reader.h
> +} // unnamed namespace
Not necessary since `C++11`. See: https://en.cppreference.com/w/cpp/string/byte/strtof

2021-04-03 17:25 UTC, yannlabou commented on sensor_data_reader.h
> +class SensorDataReader {
Sure. Let's see as the project evolves :).

2021-04-03 17:25 UTC, yannlabou commented on sensor_data_reader.h
> +        vector<double> getSensor1Y();
I had keep this very simple. No trivial getters, no functions, simple behavior-less struct, e.g.:
```
struct SensorData {
  std::vector<double> ground_truth_x_values{};
  std::vector<double> sensor_1_x_values;
  std::vector<double> ground_truth_y_values;
  std::vector<double> sensor_1_y_values;
}
```
I would avoid coupling the reader method to the data structure and implement it outside as
```
[[nodiscard]] SensorData readSensorData(std::string_view file_path) {};
```

2021-04-03 17:25 UTC, yannlabou commented on run_filter.cpp
> +    cout << sensor_1_x_values.size() << endl;
Let's static_assert at compile time.

2021-04-03 17:25 UTC, yannlabou commented on run_filter.cpp
> +    reader.readSensorData(SENSOR_DATA);
See my comment in `sensor_data_reader.h`.

2021-04-03 17:25 UTC, yannlabou commented on sensor_data_reader.cpp
> +    string ground_truth_x, sensor_1_x, ground_truth_y, sensor_1_y, line;
One declaration per line increases readability and avoids mistakes related to the C++ grammar.

2021-04-03 17:25 UTC, yannlabou commented on sensor_data_reader.cpp
> +        sensor_1_y_values.push_back(toNumber(sensor_1_y));
Use C++11 `std::stod`.

2021-04-03 17:35 UTC, yannlabou commented on CMakeLists.txt
> +project(probablistic_filters CXX)
Oh... typo. **probabilistic** :).

2021-04-03 17:41 UTC, yannlabou commented on CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 17)
But it wasn't related to the C++ standard right? Yeah... I know. We are building with a high level of warnings.

2021-04-03 19:31 UTC, robgineer commented on CMakeLists.txt
> +project(probablistic_filters CXX)
Done. 1d407087f5b8aa831108eda39ddfac09a86d6e2f

2021-04-03 19:32 UTC, robgineer commented on CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 17)
Features >= C++ 11 were not compiling ... could you check if it works on your machine without this setting?

2021-04-03 19:56 UTC, robgineer commented on CMakeLists.txt
> +target_link_libraries(run_filter sensor_data_reader)
Done. 74872f1fedda528f26b68340b34c06b0c01e31e8

Some of the settings in ```cmake/CompilerWarnings.cmake``` did not work on my machine, however.

2021-04-03 20:00 UTC, yannlabou commented on CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 17)
It worked on my machine. Please post a build log.

2021-04-03 20:06 UTC, robgineer commented on run_filter.cpp
> +    cout << sensor_1_x_values.size() << endl;
```static_assert``` for a vector size?

2021-04-03 20:09 UTC, robgineer commented on CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 17)
In file included from /usr/include/c++/5/type_traits:35:0,
                 from /home/milky/devel/workspace/run_filter.cpp:3:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^
/home/milky/devel/workspace/run_filter.cpp: In function ‘int main()’:
/home/milky/devel/workspace/run_filter.cpp:10:16: error: ‘ground_truth_x_values’ does not name a type
     const auto ground_truth_x_values = reader.getGroundTruthX();
                ^
/home/milky/devel/workspace/run_filter.cpp:11:16: error: ‘ground_truth_y_values’ does not name a type
     const auto ground_truth_y_values = reader.getGroundTruthY();
                ^
/home/milky/devel/workspace/run_filter.cpp:12:16: error: ‘sensor_1_x_values’ does not name a type
     const auto sensor_1_x_values = reader.getSensor1X();
                ^
/home/milky/devel/workspace/run_filter.cpp:13:16: error: ‘sensor_1_y_values’ does not name a type
     const auto sensor_1_y_values = reader.getSensor1Y();

2021-04-03 20:23 UTC, yannlabou commented on run_filter.cpp
> +    cout << sensor_1_x_values.size() << endl;
I taught the data set is our test data set and we definitely know the expected size. Of course if you want to log for any input data set, static_assert won't work here.

2021-04-03 20:33 UTC, robgineer commented on CMakeLists.txt
> +add_library(sensor_data_reader sensor_data_reader.cpp)
Done.

2021-04-03 20:34 UTC, robgineer commented on run_filter.cpp
> +    cout << sensor_1_x_values.size() << endl;
The output is just a placeholder indicating that the reading worked. I am sure we would have different data sets in the future.

2021-04-03 20:34 UTC, robgineer commented on sensor_data_reader.cpp
> +        sensor_1_y_values.push_back(toNumber(sensor_1_y));
Done. 0cd4d0e588c59386f577ddf63a4a3336473dffc2

2021-04-03 20:35 UTC, yannlabou commented on CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 17)
Let's check it someday by video call. I have no issue with Apple clang 12.0.0 and g++-10.

2021-04-03 20:37 UTC, robgineer commented on sensor_data_reader.h
> +using namespace std;
Great catch!! Done. 7deace27b18516acb73e4fa263e9a2d893f660ab

2021-04-03 20:37 UTC, robgineer commented on sensor_data_reader.h
> +} // unnamed namespace
Removed!

2021-04-03 20:38 UTC, robgineer commented on run_filter.h.in
> +#cmakedefine SENSOR_DATA "@PATH_TO_SENSOR_DATA@"
I see... we need an argument parser in that case... maybe something for the next PR?

2021-04-03 20:41 UTC, robgineer commented on sensor_data_reader.cpp
> +    string ground_truth_x, sensor_1_x, ground_truth_y, sensor_1_y, line;
Alright... one line per declaration it is ;)
43c8228df500b0b130b6f2ccbd54bd3d790c7f3a

2021-04-03 20:58 UTC, yannlabou commented on run_filter.h.in
> +#cmakedefine SENSOR_DATA "@PATH_TO_SENSOR_DATA@"
We don't need the next 100th arg parser that early ;). We could start simple with something like:
```
int main(int argc, char *argv[]) {
  if (argc != 2) {
    std::cerr << "usage: " << run_filter << " <file_path>\n";
    return EXIT_FAILURE;
  }
  const std::filesystem::path file_path{ argv[1] };
  const auto csv_data = ::read_sensor_data(file_path);
}
```

2021-04-03 20:58 UTC, robgineer commented on sensor_data_reader.h
> +        vector<double> getSensor1Y();
Done. bef8c1dac435a7f050bc5478d5e7df34921cb1f1

Reader renamed to Handler + trivial getters removed

2021-04-03 21:02 UTC, robgineer commented on CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 17)
Alright! It works for now (the auto declarations have been removed)

2021-04-03 21:16 UTC, robgineer commented on run_filter.h.in
> +#cmakedefine SENSOR_DATA "@PATH_TO_SENSOR_DATA@"
Alright! Done.
0da0c03058d8a7d2126ddba5cb8a25abc631a46a

2021-04-04 08:31 UTC, yannlabou commented
> Please remove this line and the next two. Sorry. I’m on my cell phone :).

Done in ece4474

2021-04-04 08:32 UTC, yannlabou commented on CMakeLists.txt
> +configure_file("run_filter.h.in" "run_filter.h")
ece4474

2021-04-04 09:30 UTC, merged