Implement bayesian filter
yannlabou/par pull request #3
Opened 2021-04-06 21:50 UTC by robgineer

2021-04-17 14:47 UTC, yannlabou requested changes

2021-04-17 14:47 UTC, yannlabou commented on bayesian_filter.cpp
> +}
Shouldn't `generateBelief` returns a belief?

2021-04-17 14:47 UTC, yannlabou commented on bayesian_filter.h
> +  Belief belief;
Should be a `private` member.

2021-04-17 14:47 UTC, yannlabou commented on bayesian_filter.cpp
> +#include <iostream>
Probably not needed here.

2021-04-17 14:47 UTC, yannlabou commented on sensor_data_handler.cpp
> +    if (values_1.size() != values_2.size()) {return 1;}
We should check it first. If this fails, the `csv_file` won't be closed.

2021-04-17 14:47 UTC, yannlabou commented on sensor_data_handler.h
> +  int writeSensorData(std::string_view filename, std::string_view column_name_1, std::vector<double> values_1,
I suggest `bool ` as return type.

2021-04-18 19:56 UTC, robgineer commented on bayesian_filter.cpp
> +}
The idea was that it should generate one and store it somewhere...

2021-04-18 19:58 UTC, robgineer commented on bayesian_filter.h
> +  Belief belief;
Well, in that case we would need the "trivial" getters that we didnt like ;) 
(We are accessing the member within ```run_flter``` directly).

2021-04-18 20:03 UTC, robgineer commented on bayesian_filter.cpp
> +#include <iostream>
Done. d51e52f237007965ab3fc1c0cba58bc5b1c917f6

2021-04-18 20:04 UTC, robgineer commented on sensor_data_handler.h
> +  int writeSensorData(std::string_view filename, std::string_view column_name_1, std::vector<double> values_1,
Done. d51e52f237007965ab3fc1c0cba58bc5b1c917f6

2021-05-01 11:44 UTC, merged